# .rubocop.yml
AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

#Metrics/MethodLength:
#  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec